version: '3'

services:
  api:
    build:
      dockerfile: ./DotNetExamProject/Dockerfile
      context: ..
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    networks:
      - app
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dotNetExamDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app

networks:
  app:
    driver: bridge
