version: '3'

services:
  api:
    build:
      dockerfile: ./DotNetExamProject/Dockerfile
      context: ..
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      DefaultConnection: Host=db;Port=5433;Database=dotNetExamDB;Username=postgres;Password=postgres,
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: dotNetExamDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
