version: '3'

services:
  api:
    build:
      dockerfile: ./DotNetExamProject/Dockerfile
      context: ..
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80